apiVersion: v1
kind: Pod

metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: igalcohen/myskagam
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myskagam-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2

    spec:
      containers:
      - name: nginx2
        image: igalcohen/myskagam
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-external
spec:
 # Expose the service on a static port on each node
 # So that we can access the service outside the cluster

  type: NodePort
 
 # When the node recives a request on the static port (30163)
 # "select pods with the label" app to set 'nginx'
 # and forward the request to one of them.

  selector:
    app: nginx
  ports:
  # three types of ports for a service
  # nodeport - a static port assigned on node
  # port - the port exposed internally in the cluster
  # targetport - the contianer port to send requests to 
    - nodePort: 30163
      port: 8082
      targetPort: 80

 