---
- name: Create my K8S Webserver Based on Nginx Not Privlieged User
  hosts: localhost

  tasks:

  - name: Pod Creation , Deployment of Pods and Service Creation 
    shell: kubectl apply -f ./deployment.yaml



